Description of biotable_clean
Home > sbtab > biotable > biotable_clean.m
biotable_clean
PURPOSE
SYNOPSIS
function data_table = biotable_clean(data_table)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
biotable_choose_items data2 = biotable_choose_items(data,ind)
biotable_metabolite_combine_replicates ----------------------------------------------------
biotable_network_interpolate
biotable_omit_outliers data = biotable_omit_outliers(data, fraction_omit_samples, fraction_omit_values)
biotable_remove
biotable_write biotable_write(data_table,basename)