Description of biotable_join_replicates
Home > sbtab > biotable > biotable_join_replicates.m
biotable_join_replicates
PURPOSE
[combined,collected] = biotable_join_replicates(data,p)
SYNOPSIS
function [combined,collected] = biotable_join_replicates(data,p)
DESCRIPTION
 [combined,collected] = biotable_join_replicates(data,p)
CROSS-REFERENCE INFORMATION
This function calls:
default DEFAULT Generate matlab command string for initialising variables
This function is called by:
biotable_combine_experiments concatenate time series
biotable_combine_replicates [data_central, data_average, data_replicates, statistics, options, data_combined, data_collected] = biotable_combine_replicates(data, options)