Description of biotable_write
Home > sbtab > biotable > biotable_write.m
biotable_write
PURPOSE
biotable_write(data_table,basename)
SYNOPSIS
function all = biotable_write(data_table,basename,options)
DESCRIPTION
 biotable_write(data_table,basename)
 export matlab data structure to standard table format for dynamic data
 EXAMPLE
 d = struct();
 d.MetaboliteName = {'A','B'}';
 d.ChebiId = {'a','b'}';
 d.SampleName = {'1','2'}';
 d.SampleTime = [0;1];
 d.DataMean = ones(2);
 d.DataStd = 0.1*ones(2);
 d.Info = {'bla','bli';'blu','bloe'};
 %OpenBis format
 T = biotable_write(d,[],struct('flag_openbis',1,'ind_use_id',2,'ExperimentCode','GM','CultivationMethod','BR','BiologicalReplicateCode','B1','TimePointType','EX','TechnicalReplicateCode','','CelLoc','CE','DataSetType','MetaboliteLCMS','ShortUnit','mM','Scale','Lin','BiID','','CG',''));
 %SBtab format
 T= biotable_write(d,[],struct('flag_openbis',0,'ind_use_id',2,'ExperimentCode','GM','CultivationMethod','BR','BiologicalReplicateCode','B1','TimePointType','EX','TechnicalReplicateCode','','CelLoc','CE','DataSetType','MetaboliteLCMS','ShortUnit','mM','Scale','Lin','BiID','','CG',''));
CROSS-REFERENCE INFORMATION
This function calls:
biotable_clean
default DEFAULT Generate matlab command string for initialising variables
This function is called by:
biotable_write_multiple