Description of demo_sbtab
Home > sbtab > demo > demo_sbtab.m
demo_sbtab
PURPOSE
SBtab - short demo: load SBtab table and show its structure
SYNOPSIS
This is a script file.
DESCRIPTION
 SBtab - short demo: load SBtab table and show its structure
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_BASEDIR SBTAB_BASEDIR - Return SBtab toolbox directory
sbtab_table_load SBTAB_TABLE_LOAD Load SBtab table from file, or generate it from a list of strings
sbtab_table_show SBTAB_TABLE_SHOW Show contents of Sbtab table
sbtab_BASEDIR SBTAB_BASEDIR Directory in which SBtab package is installed
This function is called by: