Description of default
Home > sbtab > utils > default.m
default
PURPOSE
DEFAULT Generate matlab command string for initialising variables
SYNOPSIS
function commandstring = default(varargin)
DESCRIPTION
 DEFAULT Generate matlab command string for initialising variables
 commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
 USAGE:
 eval(default('a','1','name','''cat'''));
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
biotable_combine_replicates [data_central, data_average, data_replicates, statistics, options, data_combined, data_collected] = biotable_combine_replicates(data, options)
biotable_concatenate
biotable_construct_timeseries bt = biotable_construct_timeseries(item_name,items,time,data_mean,data_std)
biotable_invent_standard_deviations
biotable_join_replicates [combined,collected] = biotable_join_replicates(data,p)
biotable_network_interpolate
biotable_read data = biotable_read(basename,n_name_columns)
biotable_write biotable_write(data_table,basename)
sbtab_document_add_column SBTAB_DOCUMENT_ADD_TABLE Add column to existing table in SBtab document.
sbtab_document_construct SBTAB_DOCUMENT_CONSTRUCT Build SBtab document object.
sbtab_document_save SBTAB_DOCUMENT_SAVE Save SBtab document to files (one for each table)
sbtab_document_save_to_one SBTAB_DOCUMENT_SAVE Save SBtab document to one file (with concatenated tables)
sbtab_table_add_column SBTAB_TABLE_ADD_COLUMN Add column to SBtab table.
sbtab_table_check SBTAB_TABLE_CHECK Check table for table type attribute being present
sbtab_table_construct SBTAB_TABLE_CONSTRUCT Construct an SBtab table object.
sbtab_table_get_column SBTAB_TABLE_GET_COLUMN Get column from an SBtab table
sbtab_table_has_column SBTAB_TABLE_GET_COLUMN Check for existence of column in an SBtab table
sbtab_table_save SBTAB_TABLE_SAVE Save SBtab table
sbtab_table_subselect_items SBTAB_SUBSELECT_ITEMS Select rows that have entries for a specific column