Description of load_unformatted_table
Home > sbtab > utils > load_unformatted_table.m
load_unformatted_table
PURPOSE
LOAD_UNFORMATTED_TABLE load data table
SYNOPSIS
function T = load_unformatted_table(filename)
DESCRIPTION
 LOAD_UNFORMATTED_TABLE load data table
 T = load_unformatted_table(filename)
 loads table (not required to have proper column headers); removes empty rows and columns
CROSS-REFERENCE INFORMATION
This function calls:
strsplit STRSPLIT Split string into pieces.
This function is called by:
sbtab_document_load_from_one SBTAB_DOCUMENT_LOAD_FROM_ONE % Load SBtab document (possibly, several tables) from one file
sbtab_table_load SBTAB_TABLE_LOAD Load SBtab table from file, or generate it from a list of strings
SOURCE CODE
function T = load_unformatted_table(filename)
% LOAD_UNFORMATTED_TABLE load data table
%
% T = load_unformatted_table(filename)
%
% loads table (not required to have proper column headers); removes empty rows and columns
fid  = fopen(filename);
if fid <0,
  error(sprintf('File %s cannot be found',filename));
end
stop = 0;
T = {};
while ~stop,
  this_line = fgetl(fid);
  if this_line == -1,
    stop = 1;
  else,
    this_line = strsplit(sprintf('\t'),this_line,'omit');
    T(size(T,1)+1,1:length(this_line)) = this_line;
  end
end
fclose(fid);
% remove empty rows and columns
keep_row = find(sum(cellfun('length',T),2));
keep_col = find(sum(cellfun('length',T),1));
T= T(keep_row,keep_col);