Description of sbtab_clean_column_headers
Home > sbtab > sbtab_utils > sbtab_clean_column_headers.m
sbtab_clean_column_headers
PURPOSE
SYNOPSIS
function column_names = sbtab_clean_column_headers(column_names)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sbtab_2_dynamic_data d = dynamic_data_2_sbtab(dynamic_data,experiment_name)
sbtab_table_construct SBTAB_TABLE_CONSTRUCT Construct an SBtab table object.
sbtab_table_show SBTAB_TABLE_SHOW Show contents of Sbtab table