Description of sbtab_document_construct
Home > sbtab > sbtab_document_construct.m
sbtab_document_construct
PURPOSE
SBTAB_DOCUMENT_CONSTRUCT Build SBtab document object.
SYNOPSIS
function my_sbtab_document = sbtab_document_construct(attributes,table_names,tables)
DESCRIPTION
 SBTAB_DOCUMENT_CONSTRUCT Build SBtab document object.
 my_sbtab_document = sbtab_document_construct(attributes,table_names,tables)
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_document_add_table SBTAB_DOCUMENT_ADD_TABLE Add table to SBtab document.
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
sbtab_document_load SBTAB_DOCUMENT_LOAD Load SBtab document from a number of files
sbtab_document_load_from_one SBTAB_DOCUMENT_LOAD_FROM_ONE % Load SBtab document (possibly, several tables) from one file
SOURCE CODE
function my_sbtab_document = sbtab_document_construct(attributes,table_names,tables)
% SBTAB_DOCUMENT_CONSTRUCT Build SBtab document object.
%
% my_sbtab_document = sbtab_document_construct(attributes,table_names,tables)
eval(default('attributes','struct'));
my_sbtab_document.attributes = attributes;
my_sbtab_document.tables     = struct;
if exist('table_names','var'),
 for it = 1:length(table_names),
    my_sbtab_document = sbtab_document_add_table(my_sbtab_document,table_names{it},tables{it});
 end
end