Description of sbtab_document_save
Home > sbtab > sbtab_document_save.m
sbtab_document_save
PURPOSE
SBTAB_DOCUMENT_SAVE Save SBtab document to files (one for each table)
SYNOPSIS
function sbtab_document_save(sbtab_document,filename,flag_latex,verbose,to_one_file)
DESCRIPTION
 SBTAB_DOCUMENT_SAVE Save SBtab document to files (one for each table)
 sbtab_document_save(sbtab_document,filename)
 filename has to be without extension
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_document_save_to_one SBTAB_DOCUMENT_SAVE Save SBtab document to one file (with concatenated tables)
sbtab_table_save SBTAB_TABLE_SAVE Save SBtab table
default DEFAULT Generate matlab command string for initialising variables
This function is called by: