Description of sbtab_table_show
Home > sbtab > sbtab_table_show.m
sbtab_table_show
PURPOSE
SBTAB_TABLE_SHOW Show contents of Sbtab table
SYNOPSIS
function sbtab_table_show(sbtab_table)
DESCRIPTION
 SBTAB_TABLE_SHOW Show contents of Sbtab table
 sbtab_table_show(sbtab_table)
 display contents of an SBtab table
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_clean_column_headers
This function is called by:
demo_sbtab SBtab - short demo: load SBtab table and show its structure
sbtab_document_show SBTAB_DOCUMENT_SHOW Display contents of an SBtab document