Description of sbtab_table_subselect_items
Home > sbtab > sbtab_table_subselect_items.m
sbtab_table_subselect_items
PURPOSE
SBTAB_SUBSELECT_ITEMS Select rows that have entries for a specific column
SYNOPSIS
function t = sbtab_table_subselect_items(t,column,sbtab_file_out,given_entry)
DESCRIPTION
 SBTAB_SUBSELECT_ITEMS Select rows that have entries for a specific column
 t = sbtab_subselect_items(t,column,sbtab_file_out,given_entry)
 reduce table to rows that have a (non-empty) entry in column [column]
 or, if [given_entry] is provided, row in which the entry of [column] matches [given_entry]
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_table_load SBTAB_TABLE_LOAD Load SBtab table from file, or generate it from a list of strings
sbtab_table_save SBTAB_TABLE_SAVE Save SBtab table
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
SOURCE CODE
function t = sbtab_table_subselect_items(t,column,sbtab_file_out,given_entry)
% SBTAB_SUBSELECT_ITEMS Select rows that have entries for a specific column
%
% t = sbtab_subselect_items(t,column,sbtab_file_out,given_entry)
%
% reduce table to rows that have a (non-empty) entry in column [column]
% or, if [given_entry] is provided, row in which the entry of [column] matches [given_entry]
eval(default('sbtab_file_out','[]'));
if isstr(t),
  t = sbtab_table_load(t);
end
if exist('given_entry','var'),
  ind_remove = find(strcmp(given_entry,t.column.column.(column))==0);
  t.column.column.(column)(ind_remove) = repmat({''},length(ind_remove),1);
end
ind = find(cellfun('length',t.column.column.(column)));
fn = fieldnames(t.column.column);
for it = 1:length(fn),
  t.column.column.(fn{it}) = t.column.column.(fn{it})(ind);
end
if length(sbtab_file_out),
  sbtab_table_save(t,struct('filename',sbtab_file_out));
end