Description of sbtab_table_construct
Home > sbtab > sbtab_table_construct.m
sbtab_table_construct
PURPOSE
SBTAB_TABLE_CONSTRUCT Construct an SBtab table object.
SYNOPSIS
function my_sbtab_table = sbtab_table_construct(attributes, column_names, columns)
DESCRIPTION
 SBTAB_TABLE_CONSTRUCT Construct an SBtab table object.
 my_sbtab_table = sbtab_table_construct(attributes, column_names, columns)
  attributes:   matlab struct defining keys and values of table attributes
  column_names: list of column names
  columns:      list of columns (each being a column of strings or numbers)
 Example:
 my_sbtab_table = sbtab_table_construct(struct('TableType','Wonder'),{'A'},{{1 2 3}'})
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_clean_column_headers
default DEFAULT Generate matlab command string for initialising variables
This function is called by:
dynamic_data_2_sbtab SBtab_doc = dynamic_data_2_sbtab(dynamic_data,experiment_name)