Description of sbtab_2_dynamic_data
Home > sbtab > sbtab_2_dynamic_data.m
sbtab_2_dynamic_data
PURPOSE
d = dynamic_data_2_sbtab(dynamic_data,experiment_name)
SYNOPSIS
function d = sbtab_2_dynamic_data(filename)
DESCRIPTION
 d = dynamic_data_2_sbtab(dynamic_data,experiment_name)
 Read SBtab file and put the data into omics data table ("biotable" data structure)
 Omics data can be related to compounds or reactions.
 For writing such files, see dynamic_data_2_sbtab.m
 For the biotable format itself, see 'help biotable'
CROSS-REFERENCE INFORMATION
This function calls:
sbtab_document_get_table SBTAB_DOCUMENT_GET_TABLE Get table from SBtab document.
sbtab_document_load_from_one SBTAB_DOCUMENT_LOAD_FROM_ONE % Load SBtab document (possibly, several tables) from one file
sbtab_table_get_column SBTAB_TABLE_GET_COLUMN Get column from an SBtab table
sbtab_clean_column_headers
This function is called by: